Add mc_xsens_plugin
mc-rtc/superbuild-extensions pull request #2
Opened 2023-11-27 17:02 UTC by arntanguy

This PR adds `XsensPlugin` and its dependencies:
- [mc_xsens_plugin@master](https://github.com/arntanguy/mc_xsens_plugin)
- When `WITH_XSENS_STREAMING=ON` it adds the `mtsdk` and `xsens_streaming` dependencies allowing for live retargetting using the Xsens MVN software. When off the plugin can still be used in conjunction with the `Replay` plugin to perform retargetting from log files

2023-11-28 08:37 UTC, gergondet requested changes

2023-11-28 08:37 UTC, gergondet commented on plugins/mc_xsens_plugin.cmake
> +endif()
This will not work well with the intended usage of `superbuild-extensions`.

Users (or other extensions) are expected to include the extra packages they want to build with so the option is implied to be `ON`.

2023-11-28 08:37 UTC, gergondet commented on plugins/mtsdk.cmake
> +set (MTSDK_URL "https://seafile.lirmm.fr/f/ee9ea17af9f8439fabc0/?dl=1")
Is there not a more "official" SDK install link?

2023-11-28 09:10 UTC, arntanguy commented on plugins/mtsdk.cmake
> +set (MTSDK_URL "https://seafile.lirmm.fr/f/ee9ea17af9f8439fabc0/?dl=1")
It's from here: https://www.movella.com/support/software-documentation
But unfortunately there is no direct link to a downloadable archive so I made a copy.

2023-11-28 09:12 UTC, arntanguy commented on plugins/mc_xsens_plugin.cmake
> +endif()
Indeed, that was a left over from where I had initially made it outside of `superbuild-extensions`. Sorry for the oversight ;)

2023-11-30 08:07 UTC, gergondet commented on plugins/mtsdk.cmake
> +set (MTSDK_URL "https://seafile.lirmm.fr/f/ee9ea17af9f8439fabc0/?dl=1")
I think we cannot redistribute it freely. I think it's better to require the user to install the sdk by themselves. In a more private setting (i.e. where we known the user have all already accepted the EULA of Movella) then we might do this install as in this example

2024-03-01 18:09 UTC, arntanguy commented
You are right. I removed the automated install of MTSDK, and added an explanation in `xsens_streaming` pointing on how to install it manually.

2024-03-01 18:09 UTC, merged